def gen_header(lef_p) -> None:
    LEF_file = lef_p.LEF_file
    name     = lef_p.name
    bits     = lef_p.bits
    depth    = lef_p.depth
    banks    = lef_p.banks
    h        = lef_p.h
    w        = lef_p.w

    LEF_file = open(LEF_file, 'w')

    LEF_file.write('# Generated by FakeRAM 2.0\n')
    LEF_file.write('VERSION 5.7 ;\n')
    LEF_file.write('BUSBITCHARS "[]" ;\n')
    LEF_file.write('PROPERTYDEFINITIONS\n')
    LEF_file.write('  MACRO width INTEGER ;\n')
    LEF_file.write('  MACRO depth INTEGER ;\n')
    LEF_file.write('  MACRO banks INTEGER ;\n')
    LEF_file.write('END PROPERTYDEFINITIONS\n')
    LEF_file.write('MACRO %s\n' % (name))
    LEF_file.write(f'  PROPERTY width {bits} ;\n')
    LEF_file.write(f'  PROPERTY depth {depth} ;\n')
    LEF_file.write(f'  PROPERTY banks {banks} ;\n')
    LEF_file.write('  FOREIGN %s 0 0 ;\n' % (name))
    LEF_file.write('  SYMMETRY X Y R90 ;\n')
    LEF_file.write('  SIZE %.3f BY %.3f ;\n' % (w,h))
    LEF_file.write('  CLASS BLOCK ;\n')
    LEF_file.close()

def gen_obs(lef_p) -> None:
    LEF_file       = lef_p.LEF_file
    mem            = lef_p.mem
    name           = lef_p.name
    metal_prefix   = lef_p.metal_prefix
    metalLayerPins = lef_p.metalLayerPins
    h              = lef_p.h
    w              = lef_p.w

    LEF_file = open(LEF_file, 'a')
    LEF_file.write('  OBS\n')

    # full rect
    pin_layer_number = metalLayerPins.replace(metal_prefix, "", 1).strip('"')
    for x in range(int(pin_layer_number)) :
        dummy = x + 1
        LEF_file.write('    LAYER %s%d ;\n' % (metal_prefix,dummy))
        LEF_file.write('    RECT 0 0 %.3f %.3f ;\n' % (w,h))
    
    # TODO
    if (mem.process.tech_nm != 7):
        LEF_file.write('    LAYER OVERLAP ;\n')
        LEF_file.write('    RECT 0 0 %.3f %.3f ;\n' % (w,h))

    LEF_file.write('  END\n')
    LEF_file.write('END %s\n' % name)
    LEF_file.write('\n')
    LEF_file.write('END LIBRARY\n')
    LEF_file.close()