from utils.gen_lef.modules.class_lefparameters import LEF_Parameters
from utils.gen_lef.lef_globals import *
from utils.gen_lef.decimal_helpers import * 

################################################################################
# LEF WRITE FUNCTION HELPER CLASS
#
# Utilities for generating a complete LEF macro for FakeRAM 2.0: header,
# power-grid straps, OBS blockage, and pin rectangles (I/O; vertical/horizontal).
# This class relies on tech/process and geometry set in LEF_Parameters (e.g., metal
# prefix, layer indices, widths/heights, manufacturing grid, file path).
# 
# Functions:
#   gen_header()                         - write LEF header, properties, open MACRO
#   gen_obs()                            - write OBS blockage, optional OVERLAP,
#                                           close MACRO and LIBRARY
#
#   gen_straps()                        - write VSS/VDD power grid pins
#   write_input_vertical_pin_to_lef()    - write INPUT pin on left/right edge
#   write_output_vertical_pin_to_lef()   - write OUTPUT pin on left/right edge
#   write_input_horizontal_pin_to_lef()  - write INPUT pin on top/bottom edge
#   write_output_horizontal_pin_to_lef() - write OUTPUT pin on top/bottom edge
################################################################################

class LEF_WriteFunctions(LEF_Parameters):
    def __init__(self, mem):
        super().__init__(mem)
    
    ### Write header ###
    def gen_header(self) -> None:
        with open(self.LEF_file, 'w') as lef_file:
            lef_file.write('# Generated by OpenFakeRAM\n')
            lef_file.write('VERSION 5.7 ;\n')
            lef_file.write('BUSBITCHARS "[]" ;\n')
            lef_file.write('PROPERTYDEFINITIONS\n')
            lef_file.write('  MACRO width INTEGER ;\n')
            lef_file.write('  MACRO depth INTEGER ;\n')
            lef_file.write('  MACRO banks INTEGER ;\n')
            lef_file.write('END PROPERTYDEFINITIONS\n')
            lef_file.write('MACRO %s\n' % (self.name))
            lef_file.write(f'  PROPERTY width {self.bits} ;\n')
            lef_file.write(f'  PROPERTY depth {self.depth} ;\n')
            lef_file.write(f'  PROPERTY banks {self.banks} ;\n')
            lef_file.write('  FOREIGN %s 0 0 ;\n' % (self.name))
            lef_file.write('  SYMMETRY X Y R90 ;\n')
            lef_file.write('  SIZE %.3f BY %.3f ;\n' % (self.w, self.mem.height_um))
            lef_file.write('  CLASS BLOCK ;\n')

    ### Write obs ###
    def gen_obs(self) -> None:
        metalLayerPins = str(max(self.metLayerHorizontalPin, 
                                self.metLayerVerticalPin, 
                                self.metLayerPowerGrid))

        with open(self.LEF_file, 'a') as lef_file:
            lef_file.write('  OBS\n')

            # full rect
            pin_layer_number = metalLayerPins.replace(self.metal_prefix, "", 1).strip('"')
            for x in range(int(pin_layer_number)):
                dummy = x + 1
                lef_file.write('    LAYER %s%d ;\n' % (self.metal_prefix, dummy))
                lef_file.write('    RECT 0 0 %.3f %.3f ;\n' % (self.w, self.mem.height_um))
            
            # TODO
            if (self.mem.process.tech_nm != 7):
                lef_file.write('    LAYER OVERLAP ;\n')
                lef_file.write('    RECT 0 0 %.3f %.3f ;\n' % (self.w, self.mem.height_um))

            lef_file.write('  END\n')
            lef_file.write('END %s\n' % self.name)
            lef_file.write('\n')
            lef_file.write('END LIBRARY\n')

    def gen_straps(self) -> None:
        pin_size              = max(self.x_pin_height, self.x_pin_width, self.y_pin_height, self.y_pin_width)
        supply_pin_width      = self.powerGridWidth_um
        supply_pin_half_width = snap_to_grid(supply_pin_width/2, self.manufacturing_grid_um)
        supply_pin_pitch      = snap_to_grid(self.powerGridPitch_um, self.manufacturing_grid_um)

        with open(self.LEF_file, 'a') as lef_file:
            if self.directionPowerGrid == 'vertical':
                # Prevent overlapped from VDD/VSS by adding pin width + x_offset
                pw_space = snap_to_grid(pin_size*2, self.manufacturing_grid_um)
                x_step = snap_to_grid(pw_space + supply_pin_pitch*2, self.manufacturing_grid_um) + self.powerGridOffset_um
                
                # Write VSS pins
                lef_file.write('  PIN VSS\n')
                lef_file.write('    DIRECTION INOUT ;\n')
                lef_file.write('    USE GROUND ;\n')
                lef_file.write('    PORT\n')
                lef_file.write('      LAYER %s%s ;\n' % (self.metal_prefix, self.metLayerPowerGrid))

                while x_step <= self.w - (pin_size*2):
                    lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                                 (x_step-supply_pin_half_width, (pin_size*2), 
                                  x_step+supply_pin_half_width, self.mem.height_um-(pin_size*2)))
                    x_step = snap_to_grid(x_step + supply_pin_pitch*2, self.manufacturing_grid_um)
            
                lef_file.write('    END\n')
                lef_file.write('  END VSS\n')

                # Write VDD pins
                x_step = snap_to_grid(pw_space + supply_pin_pitch, self.manufacturing_grid_um) + self.powerGridOffset_um
                lef_file.write('  PIN VDD\n')
                lef_file.write('    DIRECTION INOUT ;\n')
                lef_file.write('    USE POWER ;\n')
                lef_file.write('    PORT\n')
                lef_file.write('      LAYER %s%s ;\n' % (self.metal_prefix, self.metLayerPowerGrid))

                while x_step <= self.w - (pin_size*2):
                    lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                                 (x_step-supply_pin_half_width, (pin_size*2), 
                                  x_step+supply_pin_half_width, self.mem.height_um-(pin_size*2)))
                    x_step = snap_to_grid(x_step + supply_pin_pitch*2, self.manufacturing_grid_um)

                lef_file.write('    END\n')
                lef_file.write('  END VDD\n')

            else:  # horizontal power grid
                ph_space = snap_to_grid(pin_size*2, self.manufacturing_grid_um)
                y_step = snap_to_grid(ph_space + supply_pin_pitch*2, self.manufacturing_grid_um) + self.powerGridOffset_um
                
                # Write VSS pins
                lef_file.write('  PIN VSS\n')
                lef_file.write('    DIRECTION INOUT ;\n')
                lef_file.write('    USE GROUND ;\n')
                lef_file.write('    PORT\n')
                lef_file.write('      LAYER %s%s ;\n' % (self.metal_prefix, self.metLayerPowerGrid))

                while y_step <= self.mem.height_um - (pin_size*2):
                    lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                                 ((pin_size*2), y_step-supply_pin_half_width, 
                                  self.w-(pin_size*2), y_step+supply_pin_half_width))
                    y_step = snap_to_grid(y_step + supply_pin_pitch*2, self.manufacturing_grid_um)

                lef_file.write('    END\n')
                lef_file.write('  END VSS\n')

                # Write VDD pins
                y_step = snap_to_grid(ph_space + supply_pin_pitch, self.manufacturing_grid_um) + self.powerGridOffset_um
                lef_file.write('  PIN VDD\n')
                lef_file.write('    DIRECTION INOUT ;\n')
                lef_file.write('    USE POWER ;\n')
                lef_file.write('    PORT\n')
                lef_file.write('      LAYER %s%s ;\n' % (self.metal_prefix, self.metLayerPowerGrid))

                while y_step <= self.mem.height_um - (pin_size*2):
                    lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                                 ((pin_size*2), y_step-supply_pin_half_width, 
                                  self.w-(pin_size*2), y_step+supply_pin_half_width))
                    y_step = snap_to_grid(y_step + supply_pin_pitch*2, self.manufacturing_grid_um)
                    
                lef_file.write('    END\n')
                lef_file.write('  END VDD\n')

    def write_input_vertical_pin_to_lef(self, pinslot: object, pin_id, side) -> None:
        y_start   = pinslot.slot
        y_top     = d_get_add(y_start, self.y_pin_width)

        with open(self.LEF_file, 'a') as lef_file:
            lef_file.write(f'  PIN {pin_id}\n')
            lef_file.write(f'    DIRECTION INPUT ;\n')
            lef_file.write('    USE SIGNAL ;\n')
            lef_file.write('    SHAPE ABUTMENT ;\n')
            lef_file.write('    PORT\n')
            lef_file.write(f'      LAYER {self.metal_prefix}{pinslot.metLayer} ;\n')

            if side == 'left':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                             (0.0, y_start, self.y_pin_height, y_top))
            elif side == 'right':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                             (self.w - self.y_pin_height, y_start, self.w, y_top))

            lef_file.write('    END\n')
            lef_file.write(f'  END {pin_id}\n')

    def write_output_vertical_pin_to_lef(self, pinslot: object, pin_id, side) -> None:
        y_start   = pinslot.slot
        y_top     = d_get_add(y_start, self.y_pin_height)

        with open(self.LEF_file, 'a') as lef_file:
            lef_file.write(f'  PIN {pin_id}\n')
            lef_file.write(f'    DIRECTION OUTPUT ;\n')
            lef_file.write('    USE SIGNAL ;\n')
            lef_file.write('    SHAPE ABUTMENT ;\n')
            lef_file.write('    PORT\n')
            lef_file.write(f'      LAYER {self.metal_prefix}{pinslot.metLayer} ;\n')

            if side == 'left':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                             (0.0, y_start, self.y_pin_width, y_top))
            elif side == 'right':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                             (self.w - self.y_pin_width, y_start, self.w, y_top))

            lef_file.write('    END\n')
            lef_file.write(f'  END {pin_id}\n')

    def write_input_horizontal_pin_to_lef(self, pinslot: object, pin_id, side) -> None:
        x_start    = pinslot.slot
        x_right    = x_start + self.x_pin_width

        with open(self.LEF_file, 'a') as lef_file:
            lef_file.write(f'  PIN {pin_id}\n')
            lef_file.write(f'    DIRECTION INPUT ;\n')
            lef_file.write('    USE SIGNAL ;\n')
            lef_file.write('    SHAPE ABUTMENT ;\n')
            lef_file.write('    PORT\n')
            lef_file.write(f'      LAYER {self.metal_prefix}{pinslot.metLayer} ;\n')

            if side == 'top':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                            (x_start, self.mem.height_um - self.x_pin_height, x_right, self.mem.height_um))
            elif side == 'bottom':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                            (x_start, 0.0, x_right, self.x_pin_height))
                            
            lef_file.write('    END\n')
            lef_file.write(f'  END {pin_id}\n')

    def write_output_horizontal_pin_to_lef(self, pinslot: object, pin_id, side) -> None:
        x_start    = pinslot.slot
        x_right    = x_start + self.x_pin_width

        with open(self.LEF_file, 'a') as lef_file:
            lef_file.write(f'  PIN {pin_id}\n')
            lef_file.write(f'    DIRECTION OUTPUT ;\n')
            lef_file.write('    USE SIGNAL ;\n')
            lef_file.write('    SHAPE ABUTMENT ;\n')
            lef_file.write('    PORT\n')
            lef_file.write(f'      LAYER {self.metal_prefix}{pinslot.metLayer} ;\n')

            if side == 'top':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                            (x_start, self.mem.height_um - self.x_pin_height, x_right, self.mem.height_um))
            elif side == 'bottom':
                lef_file.write('      RECT %.3f %.3f %.3f %.3f ;\n' % 
                            (x_start, 0.0, x_right, self.x_pin_height))
                            
            lef_file.write('    END\n')
            lef_file.write(f'  END {pin_id}\n')

    # def main(self):
    #     self.gen_header()
    #     self.gen_straps()
    #     self.gen_obs()

# if __name__ == "__main__":
# main()